name: njsscan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - uses: nodejsscan
    - name: njsscan
      id: njsscan
      uses: ajinabraham/njsscan-action@v6
      with:
        args: '.'
